# Generated by Django 3.2.12 on 2022-03-08 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 20, 57, 176664)),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 20, 57, 177702)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 20, 57, 170625)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 20, 57, 170625)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 20, 57, 175660)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 20, 57, 168586)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 20, 57, 172843)),
        ),
    ]
